[theme]
base = "light"
primaryColor = "#141413"
backgroundColor = "#F9F6F1"
secondaryBackgroundColor = "#FFFCFA"
textColor = "#141413"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
